### PR TITLE
Traefik + Docker Socket Proxy + Consul on Host

### PR DESCRIPTION
**Pull request by tmackness**
This stack provides support for running Consul on the Host rather then in a container. I have a [readme](https://github.com/tmackness/docker-stacks/tree/master/swarm/traefik-proxy) that explains some of the issues I faced to help others.

### CODE REVIEW

**Comment by BretFisher** [comment]
Hey there, can you discuss some of the issues your seeing with consul on overlay? Note that Swarm and Overlay require fast networks (1Gb) and low latency (10ms) to work well in most cases (by default).

**Comment by tmackness** [comment]
So I was using Consul on the Host machine rather then in a Container this unable to use a overlay network to communicate. I went with this approach because of following their recommendations in their deployment guidelines.

**Comment by tmackness** [comment]
I setup each swarm server machine to run consul in server mode and each swarm worker machine to run consul agent.

**Comment by BretFisher** [comment]
I've not heard of any issues in years and I think the doc you're referencing is old and had to deal more with the poor performance of docker virtual networks many years ago. I can't see anyone talking about it on google so I'll assume it's not a problem for most installs.

I'm not a fan of running things on the host unless there's a known issue. If you were running into something real-world, I'd be more inclined to come up with a workaround.

Just to be sure, is this the same yaml as mine, just missing the consul service?

**Comment by tmackness** [comment]
Ah could well be old info. I’m on my phone but for the most part yes I think it was similar just a few changes. I wouldn’t worry about it after your previous comment. Thanks.

**Comment by BretFisher** [comment]
OK cool, I'll close this for now but if you see/find anything that would justify an example or improving docs on this potential issue, lmk. Happy Swarming!

**Pull request closed without merging**
